---
  - name: "QM things"
    hosts: localhost
    connection: local 
    tasks:
        - name: "Checkout qmk firmware" 
          ansible.builtin.git:
            repo: 'https://github.com/qmk/qmk_firmware.git'
            dest: "{{ ansible_env.HOME }}/code/qmk/qmk_firmware"
            version: master

        - name: "Checkout qmk firmware (RGBKB fork)" 
          ansible.builtin.git:
            repo: 'https://github.com/RGBKB/qmk_firmware.git'
            dest: "{{ ansible_env.HOME }}/code/rgbkb/qmk_firmware"
            version: development
        
        - name: "Copy crkbd maps"
          ansible.builtin.copy:
            src: crkbd
            dest: "{{ ansible_env.HOME }}/code/qmk/qmk_firmware/keyboards/crkbd"
        
        - name: "Copy rgbkb maps"
          ansible.builtin.copy:
            src: rgbkb/mun/
            dest: "{{ ansible_env.HOME }}/code/rgbkb/qmk_firmware/keyboards/rgbkb/mun/"
