# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Base16 Gruvbox dark, hard - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
#
decorations: buttonless
startup_mode: Fullscreen
draw_bold_text_with_bright_colors: false

cursor:
  style: Beam

colors:
  # Default colors
  primary:
    background : "#1a1b26"
    foreground : "#a9b1d6"

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black : "#32344a"
    blue : "#7aa2f7"
    cyan : "#449dab"
    green : "#9ece6a"
    magenta : "#ad8ee6"
    red : "#f7768e"
    white : "#787c99"
    yellow : "#e0af68"

  # Bright colors
  bright:
    black : "#444b6a"
    blue : "#7da6ff"
    cyan : "#0db9d7"
    green : "#b9f27c"
    magenta : "#bb9af7"
    red : "#ff7a93"
    white : "#acb0d0"
    yellow : "#ff9e64"

draw_bold_text_with_bright_colors: false

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: {{ regular }}
    style: Regular

  # Bold font face
  bold:
    family: {{ bold }}
    style: Bold

  # Italic font face
  italic:
    family: {{ italic }}
    style: Italic

  # Bold italic font face
  bold_italic:
    family: {{ bold_italic }}
    style: Bold Italic

  # Point size
  size: 13.0

window:
  opacity: 0.95
