---
# tasks file for role-shell
- name: Install Alacritty arch
  become: yes
  when: ansible_facts['distribution'] == 'Archlinux'
  community.general.pacman:
    name:
      - alacritty
    state: present

- name: Install Alacritty osx
  when: ansible_facts['distribution'] == 'MacOSX'
  community.general.homebrew_cask:
    name:
      - alacritty
    state: present

- name: Get the user shell
  ansible.builtin.debug:
    var: ansible_facts['user_shell']

- name: Source shell functions file in bash_profile
  when: ansible_facts['user_shell'] == '/bin/bash'
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    regexp: "source %HOME/.shell_functions"
    line: "if [ -f $HOME/.shell_functions ]; then . $HOME/.shell_functions; fi"

- name: Source shell functions file in zshrc 
  when: ansible_facts['user_shell'] == '/bin/zsh'
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "source %HOME/.shell_functions"
    line: "if [ -f $HOME/.shell_functions ]; then . $HOME/.shell_functions; fi"

- name: Copy shell functions file to home directory
  copy:
    src: shell_functions
    dest: "{{ ansible_env.HOME }}/.shell_functions"
  

