{ config, pkgs, lib, ... }:

let
  # Single source for tom's home dir — no /home/tom hardcoding below.
  homeDir = config.users.users.tom.home;

  # Official Bambu Studio from the upstream AppImage (NVIDIA-EGL fixed). The
  # nixpkgs bambu-studio build renders a blank 3D bed here — see the pkg file.
  bambu-studio-appimage = pkgs.callPackage ../../pkgs/bambu-studio-appimage.nix { };
in

# ------------------------------------------------------------------
# minerva-only system config that must SURVIVE a reinstall.
# ------------------------------------------------------------------
# hardware-minerva.nix gets clobbered by nixos-generate-config at
# install time, so anything hand-written for this host lives here
# instead: swap strategy, extra data drives, desktop-only apps.
# (nvidia.nix is the same idea for the GPU stack.)

{
  imports = [
    ./hardware.nix              # generated by nixos-generate-config at install time
    ../../modules/nvidia.nix    # Blackwell dGPU: open module + recent kernel
    ../../modules/code-drive.nix
    ../../modules/storage-drive.nix  # 4TB cold-archive btrfs (label "storage")
    # ollama-cuda is a huge uncached compile. It (and hyprland) hit random
    # cc1plus segfaults during the 2026-07-14 USB-installer build — NOT bad
    # RAM: 3 clean memtest86+ passes cleared it, and the delta was the
    # installer env (BIOS microcode 0x110 vs the installed 0x121; swapless
    # RAM-rootfs installer vs 31G zram here). Builds clean on the installed
    # system. NOTE: ai.nix also provides beads (bd).
    ../../modules/ai.nix      # ollama-cuda, beads — big-GPU host only
    ../../modules/webcam.nix    # EMEET SmartCam S600 tooling + OBS virtual cam
    ../../modules/whisper-dictate.nix  # whisper.cpp voice dictation (F13 toggle)
    ../../modules/root-snapshots.nix   # hourly btrbk snapshots of @ + @home
    # INSTALL DAY: uncomment once the disk is LUKS-partitioned and
    # nixos-generate-config has written the cryptroot device into
    # hardware.nix — the module fails eval without a device (see
    # README "minerva install").
    # ../../modules/luks.nix
  ];

  # ---- Memtest86+ in the boot menu ----------------------------------
  # Added 2026-07-14 after random cc1plus segfaults during the USB-installer
  # reinstall (two hyprland, one ollama ggml-cuda) that built clean on t480.
  # Root cause was installer-env, not hardware: 3 clean memtest86+ passes
  # cleared the RAM, and the installed system (newer microcode 0x121, 31G
  # zram swap) builds the same drvs fine. Tester kept a reboot away anyway.
  boot.loader.systemd-boot.memtest86.enable = true;

  # ---- Ethernet: Killer E5000 5GbE (2026-07-14) --------------------
  # The onboard NIC (PCI 10ec:5000, "Killer E5000") is a rebadged
  # Realtek RTL8126A and the in-kernel r8169 driver drives it fine — but
  # r8169's PCI id-table only auto-matches the plain RTL8126 (10ec:8126),
  # NOT the Killer's 10ec:5000, so nothing bound and no interface was
  # created. Force-load r8169 and feed it the extra id via new_id at
  # boot; enp130s0 then comes up and NetworkManager handles DHCP.
  # Drop this once nixpkgs' kernel carries 10ec:5000 in the id-table.
  boot.kernelModules = [ "r8169" ];
  systemd.services.killer-e5000-bind = {
    description = "Bind r8169 to the Killer E5000 NIC (PCI 10ec:5000)";
    wantedBy = [ "network-pre.target" ];
    before = [ "network-pre.target" ];
    after = [ "systemd-modules-load.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # new_id rescans and binds all matching unbound devices; a repeat
      # write (id already registered) returns EEXIST, hence `|| true`.
      ExecStart = "${pkgs.bash}/bin/sh -c 'echo 10ec 5000 > /sys/bus/pci/drivers/r8169/new_id || true'";
    };
  };

  # ---- WiFi: off by default (minerva is Ethernet-only) -------------
  # Being dual-homed on WiFi + Ethernet on one subnet caused asymmetric
  # routing / flaky connectivity (it broke the OrcaSlicer <-> A1 printer
  # MQTT session). A desktop only needs the wired Killer NIC above, so switch
  # the radio off at every boot. Re-enable on demand with `nmcli radio wifi
  # on` — it stays on until the next reboot, when this turns it back off.
  systemd.services.disable-wifi = {
    description = "Turn the WiFi radio off at boot (minerva is Ethernet-only)";
    after = [ "NetworkManager.service" ];
    wants = [ "NetworkManager.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.networkmanager}/bin/nmcli radio wifi off";
    };
  };

  # ---- Root snapshots: plain btrfs pool, no LUKS mapper -------------
  # minerva's root is a whole-drive btrfs pool labelled "nixos" (no LUKS);
  # override the module's cryptroot default.
  tomfordweb.root-snapshots.device = "/dev/disk/by-label/nixos";

  # ---- OpenRGB: one daemon for all the RGB bullshit -----------------
  # MSI Mystic Light (Z890 GAMING PLUS WIFI, USB 0db0:0076), Logitech
  # Yeti Orb, GPU/RAM zones over i2c. motherboard="intel" loads
  # i2c-dev + i2c-i801 so SMBus zones are reachable. The Keychron V0
  # Ultra is QMK — OpenRGB only sees it with OpenRGB-QMK firmware;
  # stock firmware stays on VIA. Verify: openrgb --list-devices.
  services.hardware.openrgb = {
    enable = true;
    package = pkgs.openrgb-with-all-plugins;
    motherboard = "intel";
  };

  # ---- Swap: zram, no swap partition -------------------------------
  # 64 GB RAM, zram0. Compressed
  # in-RAM swap; no disk partition to manage.
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # ---- storage drive lives in modules/storage-drive.nix --------------
  # (WD 4TB died 2026-07-14; replaced with a Fanxiang S101 4TB SSD.)

  # ---- Steam --------------------------------------------------------
  # programs.steam (not home.packages) because it needs the 32-bit
  # graphics stack and system-level driver plumbing.
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = false;
  };
  hardware.graphics.enable32Bit = true;

  # ---- OpenTabletDriver — input device config/firmware via its GUI.
  hardware.opentabletdriver.enable = true;

  # ---- ollama + beads live in modules/ai.nix ------------------------

  # ---- SMB share on the GL.iNet router (was ops/local.smb_mount.yml) -
  # Credentials must NOT live in the nix store. One-time post-install:
  #   sudo mkdir -p /etc/nixos-secrets
  #   printf 'username=dubious\npassword=%s\n' \
  #     "$(op read 'op://tomfordweb/Dubious Samba/password')" \
  #     | sudo tee /etc/nixos-secrets/dubious-smb >/dev/null
  #   sudo chmod 600 /etc/nixos-secrets/dubious-smb
  fileSystems."/mnt/dubious-smb" = {
    device = "//192.168.8.1/dubious";
    fsType = "cifs";
    options = [
      "credentials=/etc/nixos-secrets/dubious-smb"
      "uid=1000"
      "gid=1000"
      "nofail"
      "noauto"
      "x-systemd.automount"
      "x-systemd.idle-timeout=300"
    ];
  };
  environment.systemPackages = [
    pkgs.cifs-utils
    pkgs.socat            # bin/hypr-monitor-repaint taps Hyprland's socket2
                          # event stream to repaint DP monitors after a KVM switch
    # Official Bambu Studio via the upstream AppImage. Replaces the nixpkgs
    # `bambu-studio` build, which renders a BLANK 3D bed on this host (in-build
    # bug — GL stack is fine: glxgears/glxinfo work, blank even under sw-render).
    # The AppImage needed an NVIDIA-EGL fix to render — details in the pkg file.
    bambu-studio-appimage
    pkgs.orca-slicer     # Bambu Studio fork — alternative slicer for the A1
                         # (AMS, multicolor). Kept alongside as a fallback.
  ];

  # ---- Daily offsite/local backups (was ops/local.backup-strategy.yml)
  # NixOS has no /etc/cron.daily; run the ops scripts from the code
  # drive via systemd timers instead. Scripts stay in ops (single source
  # of truth); ConditionPathExists keeps boots clean before the code
  # drive is mounted/cloned. Both write to /mnt/storage. Machine-local SSH
  # target details live in /etc/nixos-secrets/ops-droplet.env:
  #   OPS_DROPLET_SSH_HOST=<local ssh alias>
  systemd.services.download-droplet-backups = {
    description = "Sync production droplet backups to /mnt/storage";
    path = with pkgs; [ bash coreutils findutils rsync openssh getent ];
    serviceConfig = {
      Type = "oneshot";
      EnvironmentFile = "-/etc/nixos-secrets/ops-droplet.env";
      ExecStart = "${pkgs.bash}/bin/bash ${homeDir}/code/tomfordweb/ops/files/downloadBackups";
    };
    unitConfig = {
      ConditionPathExists = "${homeDir}/code/tomfordweb/ops/files/downloadBackups";
      # never write into an unmounted /mnt/storage (root subvol)
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
    };
  };
  systemd.timers.download-droplet-backups = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  systemd.services.backup-local-state = {
    description = "Back up beads DBs + Claude config to /mnt/storage";
    path = with pkgs; [ bash coreutils findutils rsync gnutar gzip jq libnotify getent ]
      ++ [ "/run/wrappers" ];  # su (for the desktop notification)
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash ${homeDir}/code/tomfordweb/ops/files/backupLocalState";
    };
    unitConfig = {
      ConditionPathExists = "${homeDir}/code/tomfordweb/ops/files/backupLocalState";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
    };
  };
  systemd.timers.backup-local-state = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  # ---- daily 3mf sweep to the storage drive (dotfiles-577) -----------
  # bin/sync-3mf copies every *.3mf under ~ to /mnt/storage/3d/3mf-sync
  # (copy-only archive — never deletes). Runs as tom; skips cleanly when
  # the drive is absent.
  systemd.services.sync-3mf = {
    description = "Archive ~ *.3mf files to /mnt/storage/3d/3mf-sync";
    path = with pkgs; [ bash coreutils findutils rsync util-linux ];
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      ExecStart = "${pkgs.bash}/bin/bash ${homeDir}/code/tomfordweb/dotfiles/bin/sync-3mf";
    };
    unitConfig = {
      ConditionPathExists = "${homeDir}/code/tomfordweb/dotfiles/bin/sync-3mf";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
    };
  };
  systemd.timers.sync-3mf = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  # ---- nightly MOVE of Downloads *.stl/*.3mf to /mnt/storage/3d (dotfiles-44y)
  # bin/move-3d-downloads relocates finished model files OUT of the Downloads
  # inbox onto the storage drive (flat). Distinct from sync-3mf (a copy
  # archive): this REMOVES the source once it is safely on the drive. On a
  # name clash the destination wins and the source stays in Downloads.
  # Scheduled at 02:00, NOT midnight: sync-3mf still copies Downloads *.3mf at
  # 00:00, so staggering avoids a file vanishing mid-copy under sync-3mf.
  systemd.services.move-3d-downloads = {
    description = "Move ~/Downloads *.stl/*.3mf to /mnt/storage/3d";
    path = with pkgs; [ bash coreutils findutils rsync util-linux ];
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      ExecStart = "${pkgs.bash}/bin/bash ${homeDir}/code/tomfordweb/dotfiles/bin/move-3d-downloads";
    };
    unitConfig = {
      ConditionPathExists = "${homeDir}/code/tomfordweb/dotfiles/bin/move-3d-downloads";
      ConditionPathIsMountPoint = "/mnt/storage";
      OnFailure = "backup-notify-failure@%n.service";
    };
  };
  systemd.timers.move-3d-downloads = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*-*-* 02:00:00";
      Persistent = true;
    };
  };

  # ---- red "on fire" alert on ANY backup failure (dotfiles-tki) ------
  # The backup scripts' own notify-send fires only on their LAST line
  # (completion), and the OPS_DROPLET_SSH_HOST :?-exit dies before ever
  # reaching it — so failures were silent. systemd knows the real exit
  # code, so hang this template off each unit's OnFailure=. It fires a
  # mako urgency=critical toast (red border + dark-red bg + persistent,
  # already styled that way in config/mako/config) naming the dead unit.
  # Runs as tom with the session bus address so notify-send reaches the
  # graphical session. %n of the failing unit → this template's instance.
  systemd.services."backup-notify-failure@" = {
    description = "🔥 critical desktop alert when %i fails";
    serviceConfig = {
      Type = "oneshot";
      User = "tom";
      Environment = "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus";
    };
    scriptArgs = "%i";
    script = ''
      ${pkgs.libnotify}/bin/notify-send \
        --urgency=critical --expire-time=0 --icon=dialog-error \
        --app-name=backup-monitor \
        "🔥🔥 BACKUP FAILED 🔥🔥" \
        "$1 exited non-zero — data may NOT be backed up.
      Check: journalctl -u $1 -n 30"
    '';
  };
}
