---
- name: install nvim deps (mac)
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew:
    name:
      - tmux
      - ripgrep
      - stylua
      - fortune
      - fd
    state: present

- name: Install nvm for intellisense server
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install nvim npm dependencies
  community.general.npm:
    name: prettier
    global: yes

- name: Create nvim config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: Install my new nvim config
  tags: ["vimrc", "dotfiles"]
  copy:
    src: nvim-0.9/
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
