---
- name: install nvim deps (mac)
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew:
    name:
      - tmux
      - ripgrep
      - stylua
      - fortune
      - fd
    state: present

- name: install nvim deps (pop)
  when: ansible_distribution == 'Pop!_OS'
  become: yes
  apt:
    name:
      - ripgrep
      - fortune
      - php-codesniffer
    state: present

- name: Download phpstan phar
  when: ansible_distribution == 'Pop!_OS'
  ansible.builtin.get_url:
    url: https://github.com/phpstan/phpstan/raw/HEAD/phpstan.phar
    dest: /usr/local/bin/phpstan
    mode: 'a+x'

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.10 && nvm alias default 0.10"
    creates=/home/{{ ansible_user_id }}/.nvm/alias

# - name: Install nvm for intellisense server
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#   args:
#     creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

- name: install shellcheck for lsp
  community.general.npm:
    # Note: could use latest but I am stuck on node 16 for work still.
    name: shellcheck@1.1.0
    global: yes

- name: install pip beautysh
  # sudo -H pip3 install beautysh
  ansible.builtin.pip:
    name: beautysh

- name: install prettier for lsp
  community.general.npm:
    name: prettier
    global: yes

- name: install nginxbeautifier for lsp
  community.general.npm:
    name: nginxbeautifier
    global: yes

- name: Create nvim config directory
  file:
    path: '{{ ansible_env.HOME }}/.config/nvim'
    state: directory

- name: Install my new nvim config
  tags: ['vimrc', 'dotfiles']
  copy:
    src: nvim-0.9/
    dest: '{{ ansible_env.HOME }}/.config/nvim/'
