---
- name: Install
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  community.general.pacman:
    name:
      - ruby
      - tmux
    state: present

- name: Install
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew:
    name:
      - ruby
      - tmux
      - tmuxinator
    state: present

- name: Install
  when: 
    - ansible_distribution == 'Pop!_OS'
    - ansible_distribution == 'Ubuntu'
  become: yes
  apt:
    name:
      - ruby
      - tmux
      - tmuxinator
    state: present

# tasks file for role-tmux
- name: Copy tmux config
  tags: ["dotfiles", "tmux-conf"]
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0640

- name: Move tmuxinator configs
  copy:
    src: tmuxinator/
    dest: "{{ ansible_env.HOME }}/.config/tmuxinator/"
