---
- name: Install
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  community.general.pacman:
    name:
      - ruby
      - tmux
    state: present

- name: Install
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew:
    name:
      - ruby
      - tmux
      - tmuxinator
    state: present

- name: Install
  when: ansible_distribution == 'Pop!_OS'
  become: yes
  apt:
    name:
      - ruby
      - tmux
      - tmuxinator
    state: present

# NOTE: probably works on all linux distros
- name: Install tmuxinator for tmux project scaffolding
  when: ansible_facts['distribution'] == 'Archlinux'
  community.general.gem:
    name: tmuxinator
    state: present

- name: Create an alias for tmuxinator
  ansible.builtin.lineinfile:
    dest: '{{ ansible_env.HOME }}/.shell_functions'
    regexp: '^alias t8r='
    line: "alias t8r='tmuxinator'"

# NOTE: this works on arch, your experience may vary.
# If you get errors about tmuxinator not found, you probably can't execute rubygems from path.
- name: Ensure ruby is in the path
  when: ansible_facts['distribution'] == 'Archlinux'
  ansible.builtin.lineinfile:
    dest: '{{ ansible_env.HOME }}/.shell_functions'
    regexp: '^export PATH=${PATH}:${HOME}/.local/share/gem/ruby/3.0.0/bin'
    line: 'export PATH=${PATH}:${HOME}/.local/share/gem/ruby/3.0.0/bin'

# tasks file for role-tmux
- name: Copy tmux config
  tags: ['dotfiles']
  copy:
    src: tmux.conf
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    mode: 0640

- name: Move tmuxinator configs
  copy:
    src: tmuxinator/
    dest: '{{ ansible_env.HOME }}/.config/tmuxinator/'
