---
- name: Install tmuxinator dependencies
  community.general.pacman:
    name:
      - ruby
    state: present

- name: Install tmuxinator for tmux project scaffolding
  community.general.gem:
    name: tmuxinator
    state: present

- name: Create an alias for tmuxinator
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    path: /etc/selinux/config
    regexp: '^alias t8r='
    line: "alias t8r='tmuxinator'"

- name: Ensure ruby is in the path
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    path: /etc/selinux/config
    regexp: '^export PATH=${PATH}:${HOME}/.local/share/gem/ruby/3.0.0/bin'
    line: "export PATH=${PATH}:${HOME}/.local/share/gem/ruby/3.0.0/bin"

# tasks file for role-tmux
- name: Copy tmux config
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0640

- name: Move tmuxinator configs
  copy:
    src: tmuxinator/
    dest: "{{ ansible_env.HOME }}/.config/tmuxinator/"

